# **Libraries Importing**

In [1]:
#import libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.feature_selection import SelectKBest, chi2

#preset
sns.set_palette("pastel")

# **Dataset Importing**

In [2]:
# Replace with the full path to your local CSV file
file_path = "D:/hp/Documents/Practicum/Code/Dataset/df_kids_DROP_INVALID_FS.csv"

# Read the first line to count the number of columns
with open(file_path, 'r', encoding='utf-8') as x:
    ncols = len(x.readline().strip().split(','))

# Load CSV using the correct number of columns
df_kids_DROP_INVALID_FS = pd.read_csv(file_path, usecols=range(0, ncols))

# Display the DataFrame
df_kids_DROP_INVALID_FS.head()

,UMUR (BULAN),BANGSA,AGAMA,JANTINA,PENDAPATAN KELUARGA,STATUS PEMAKANAN,DAERAH,JENIS TASKA,TASKA_LOKASI,BMI
0,60,Melayu,Islam,LELAKI,M40,Malpemakanan,Seberang Perai Tengah,TASKA Institusi,BANDAR,Risiko berlebihan berat badan
1,53,Melayu,Islam,PEREMPUAN,B40,Malpemakanan,Seberang Perai Tengah,TASKA Di Rumah,BANDAR,Risiko berlebihan berat badan
2,52,Melayu,Islam,PEREMPUAN,B40,Malpemakanan,Seberang Perai Tengah,TASKA Institusi,BANDAR,Obes
3,58,Melayu,Islam,LELAKI,B40,Malpemakanan,Daerah Barat Daya,"TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, Y...",LUAR BANDAR,Berlebihan berat badan
4,56,Melayu,Islam,PEREMPUAN,B40,Malpemakanan,Daerah Barat Daya,"TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, Y...",LUAR BANDAR,Berat badan normal

In [3]:
# Replace with the full path to your local CSV file
file_path = "D:/hp/Documents/Practicum/Code/Dataset/df_kids_RP_MODE_FS.csv"

# Read the first line to count the number of columns
with open(file_path, 'r', encoding='utf-8') as x:
    ncols = len(x.readline().strip().split(','))

# Load CSV using the correct number of columns
df_kids_RP_MODE_FS = pd.read_csv(file_path, usecols=range(0, ncols))

# Display the DataFrame
df_kids_RP_MODE_FS.head()

,UMUR (BULAN),BANGSA,AGAMA,JANTINA,PENDAPATAN KELUARGA,STATUS PEMAKANAN,DAERAH,JENIS TASKA,TASKA_LOKASI,BMI
0,60,Melayu,Islam,LELAKI,M40,Malpemakanan,Seberang Perai Tengah,TASKA Institusi,BANDAR,Risiko berlebihan berat badan
1,54,Melayu,Islam,LELAKI,B40,Malpemakanan,Seberang Perai Tengah,TASKA Institusi,BANDAR,Berlebihan berat badan
2,53,Melayu,Islam,PEREMPUAN,B40,Malpemakanan,Seberang Perai Tengah,TASKA Di Rumah,BANDAR,Risiko berlebihan berat badan
3,52,Melayu,Islam,PEREMPUAN,B40,Malpemakanan,Seberang Perai Tengah,TASKA Institusi,BANDAR,Obes
4,58,Melayu,Islam,LELAKI,B40,Malpemakanan,Daerah Barat Daya,"TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, Y...",LUAR BANDAR,Berlebihan berat badan

# **Feature Selection Model**

## Strategy: Drop Invalid Data

In [4]:
X = df_kids_DROP_INVALID_FS.drop(columns=['BMI'])
y = df_kids_DROP_INVALID_FS['BMI']

In [5]:
le = LabelEncoder()
X_encoded = X.apply(lambda col: le.fit_transform(col.astype(str)))
y_encoded = le.fit_transform(y)

chi2_selector = SelectKBest(score_func=chi2, k='all')
chi2_selector.fit(X_encoded, y_encoded)

SelectKBest(k='all', score_func=<function chi2 at 0x000001E143E8B600>)

In [6]:
scores = pd.DataFrame({
    'Feature': X.columns,
    'Chi2 Score': chi2_selector.scores_,
    'p-value': chi2_selector.pvalues_
}).sort_values(by='p-value')

scores['Significant (p ≤ 0.05)'] = scores['p-value'] <= 0.05

print(scores)

               Feature  Chi2 Score       p-value  Significant (p ≤ 0.05)
5     STATUS PEMAKANAN  111.165085  2.324056e-22                    True
7          JENIS TASKA   75.638742  6.843836e-15                    True
0         UMUR (BULAN)   37.756616  4.222732e-07                    True
8         TASKA_LOKASI   29.488838  1.858993e-05                    True
4  PENDAPATAN KELUARGA    8.123267  1.495717e-01                   False
6               DAERAH    6.853263  2.317841e-01                   False
1               BANGSA    4.664687  4.581556e-01                   False
2                AGAMA    1.758343  8.814691e-01                   False
3              JANTINA    1.044921  9.588618e-01                   False

## Strategy: Replace Invalid Data with Mode

In [7]:
X = df_kids_RP_MODE_FS.drop(columns=['BMI'])
y = df_kids_RP_MODE_FS['BMI']

In [8]:
le = LabelEncoder()
X_encoded = X.apply(lambda col: le.fit_transform(col.astype(str)))
y_encoded = le.fit_transform(y)

chi2_selector = SelectKBest(score_func=chi2, k='all')
chi2_selector.fit(X_encoded, y_encoded)

SelectKBest(k='all', score_func=<function chi2 at 0x000001E143E8B600>)

In [9]:
scores = pd.DataFrame({
    'Feature': X.columns,
    'Chi2 Score': chi2_selector.scores_,
    'p-value': chi2_selector.pvalues_
}).sort_values(by='p-value')

scores['Significant (p ≤ 0.05)'] = scores['p-value'] <= 0.05

print(scores)

               Feature  Chi2 Score       p-value  Significant (p ≤ 0.05)
7          JENIS TASKA   49.240572  1.981666e-09                    True
0         UMUR (BULAN)   38.418721  3.108607e-07                    True
8         TASKA_LOKASI   35.611670  1.135742e-06                    True
5     STATUS PEMAKANAN   26.353138  7.620823e-05                    True
6               DAERAH    6.371485  2.717309e-01                   False
4  PENDAPATAN KELUARGA    4.991910  4.168684e-01                   False
1               BANGSA    4.885767  4.299800e-01                   False
2                AGAMA    2.590617  7.627904e-01                   False
3              JANTINA    2.503850  7.759151e-01                   False

# Dataset with Feature Selected Export

In [10]:
# Replace with the full path to your local CSV file
file_path = "D:/hp/Documents/Practicum/Code/Dataset/df_kids_DROP_INVALID.csv"

# Read the first line to count the number of columns
with open(file_path, 'r', encoding='utf-8') as x:
    ncols = len(x.readline().strip().split(','))

# Load CSV using the correct number of columns
df_kids_DROP_INVALID = pd.read_csv(file_path, usecols=range(0, ncols))

# Display the DataFrame
df_kids_DROP_INVALID.head()

,UMUR (BULAN),BANGSA,AGAMA,JANTINA,PENDAPATAN KELUARGA,STATUS PEMAKANAN,DAERAH,JENIS TASKA,TASKA_LOKASI,BMI,banana_price,papaya_price,rice_price,bread_price,fish_price,chicken_price,carrot_price,tomato_price,cauliflower_price,milk_price
0,60,Melayu,Islam,LELAKI,M40,Malpemakanan,Seberang Perai Tengah,TASKA Institusi,BANDAR,Risiko berlebihan berat badan,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
1,53,Melayu,Islam,PEREMPUAN,B40,Malpemakanan,Seberang Perai Tengah,TASKA Di Rumah,BANDAR,Risiko berlebihan berat badan,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
2,52,Melayu,Islam,PEREMPUAN,B40,Malpemakanan,Seberang Perai Tengah,TASKA Institusi,BANDAR,Obes,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
3,58,Melayu,Islam,LELAKI,B40,Malpemakanan,Daerah Barat Daya,"TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, Y...",LUAR BANDAR,Berlebihan berat badan,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9
4,56,Melayu,Islam,PEREMPUAN,B40,Malpemakanan,Daerah Barat Daya,"TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, Y...",LUAR BANDAR,Berat badan normal,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9

In [11]:
# Replace with the full path to your local CSV file
file_path = "D:/hp/Documents/Practicum/Code/Dataset/df_kids_RP_MODE.csv"

# Read the first line to count the number of columns
with open(file_path, 'r', encoding='utf-8') as x:
    ncols = len(x.readline().strip().split(','))

# Load CSV using the correct number of columns
df_kids_RP_MODE = pd.read_csv(file_path, usecols=range(0, ncols))

# Display the DataFrame
df_kids_RP_MODE.head()

,UMUR (BULAN),BANGSA,AGAMA,JANTINA,PENDAPATAN KELUARGA,STATUS PEMAKANAN,DAERAH,JENIS TASKA,TASKA_LOKASI,BMI,banana_price,papaya_price,rice_price,bread_price,fish_price,chicken_price,carrot_price,tomato_price,cauliflower_price,milk_price
0,60,Melayu,Islam,LELAKI,M40,Malpemakanan,Seberang Perai Tengah,TASKA Institusi,BANDAR,Risiko berlebihan berat badan,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
1,54,Melayu,Islam,LELAKI,B40,Malpemakanan,Seberang Perai Tengah,TASKA Institusi,BANDAR,Berlebihan berat badan,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
2,53,Melayu,Islam,PEREMPUAN,B40,Malpemakanan,Seberang Perai Tengah,TASKA Di Rumah,BANDAR,Risiko berlebihan berat badan,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
3,52,Melayu,Islam,PEREMPUAN,B40,Malpemakanan,Seberang Perai Tengah,TASKA Institusi,BANDAR,Obes,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
4,58,Melayu,Islam,LELAKI,B40,Malpemakanan,Daerah Barat Daya,"TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, Y...",LUAR BANDAR,Berlebihan berat badan,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9

In [12]:
df_kids_DROP_INVALID = df_kids_DROP_INVALID.drop(columns=['DAERAH', 'PENDAPATAN KELUARGA', 'AGAMA', 'JANTINA', 'BANGSA'])
df_kids_RP_MODE = df_kids_RP_MODE.drop(columns=['DAERAH', 'PENDAPATAN KELUARGA', 'AGAMA', 'JANTINA', 'BANGSA'])

In [14]:
df_kids_DROP_INVALID.head()

,UMUR (BULAN),STATUS PEMAKANAN,JENIS TASKA,TASKA_LOKASI,BMI,banana_price,papaya_price,rice_price,bread_price,fish_price,chicken_price,carrot_price,tomato_price,cauliflower_price,milk_price
0,60,Malpemakanan,TASKA Institusi,BANDAR,Risiko berlebihan berat badan,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
1,53,Malpemakanan,TASKA Di Rumah,BANDAR,Risiko berlebihan berat badan,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
2,52,Malpemakanan,TASKA Institusi,BANDAR,Obes,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
3,58,Malpemakanan,"TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, Y...",LUAR BANDAR,Berlebihan berat badan,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9
4,56,Malpemakanan,"TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, Y...",LUAR BANDAR,Berat badan normal,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9

In [15]:
df_kids_RP_MODE.head()

,UMUR (BULAN),STATUS PEMAKANAN,JENIS TASKA,TASKA_LOKASI,BMI,banana_price,papaya_price,rice_price,bread_price,fish_price,chicken_price,carrot_price,tomato_price,cauliflower_price,milk_price
0,60,Malpemakanan,TASKA Institusi,BANDAR,Risiko berlebihan berat badan,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
1,54,Malpemakanan,TASKA Institusi,BANDAR,Berlebihan berat badan,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
2,53,Malpemakanan,TASKA Di Rumah,BANDAR,Risiko berlebihan berat badan,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
3,52,Malpemakanan,TASKA Institusi,BANDAR,Obes,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
4,58,Malpemakanan,"TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, Y...",LUAR BANDAR,Berlebihan berat badan,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9

In [16]:
error_count = df_kids_DROP_INVALID['STATUS PEMAKANAN'].str.contains('Error/Tiada Data').sum()
print(f"Number of 'Error/Tiada Data' in 'STATUS PEMAKANAN': {error_count}")

Number of 'Error/Tiada Data' in 'STATUS PEMAKANAN': 0

In [17]:
error_count = df_kids_RP_MODE['STATUS PEMAKANAN'].str.contains('Error/Tiada Data').sum()
print(f"Number of 'Error/Tiada Data' in 'STATUS PEMAKANAN': {error_count}")

Number of 'Error/Tiada Data' in 'STATUS PEMAKANAN': 3

In [ ]:
export_path = "D:/hp/Documents/Practicum/Code/Dataset/DROP_INVALID_AfterFS.csv"
df_kids_DROP_INVALID.to_csv(export_path, index=False)

export_path = "D:/hp/Documents/Practicum/Code/Dataset/RP_MODE_AfterFS.csv"
df_kids_RP_MODE.to_csv(export_path, index=False)