In [1]:
#import libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

#preset
sns.set_palette("pastel")

In [ ]:
file_path = "D:/hp/Documents/Practicum/Code/Dataset/kids_price.csv"

# Read the first line to count the number of columns
with open(file_path, 'r', encoding='utf-8') as x:
    ncols = len(x.readline().strip().split(','))

# Load CSV using the correct number of columns
df_kids = pd.read_csv(file_path, usecols=range(0, ncols))

# Display the DataFrame
df_kids.head()

,UMUR (BULAN),BANGSA,AGAMA,JANTINA,PENDAPATAN KELUARGA,GAJI BAPA,GAJI IBU,GAJI PENJAGA,STATUS PEMAKANAN,DAERAH,...,banana_price,papaya_price,rice_price,bread_price,fish_price,chicken_price,carrot_price,tomato_price,cauliflower_price,milk_price
0,60,Melayu,Islam,LELAKI,M40,"RM 4,000 - RM 6,999","RM 4,000 - RM 6,999","RM 4,000 - RM 6,999",Malpemakanan,Seberang Perai Tengah,...,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
1,54,Melayu,Islam,LELAKI,Tiada Maklumat,"RM 10,000 dan ke atas","RM 4,000 - RM 6,999","RM 4,000 - RM 6,999",Malpemakanan,Seberang Perai Tengah,...,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
2,53,Melayu,Islam,PEREMPUAN,B40,"RM 1,000 - RM 3,999","RM 1,000 - RM 3,999","RM 1,000 - RM 3,999",Malpemakanan,Seberang Perai Tengah,...,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
3,52,Melayu,Islam,PEREMPUAN,B40,"RM 1,000 - RM 3,999","RM 1,000 - RM 3,999","RM 1,000 - RM 3,999",Malpemakanan,Seberang Perai Tengah,...,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
4,58,Melayu,Islam,LELAKI,B40,"RM 1,000 - RM 3,999",TIADA MAKLUMAT GAJI,"RM 1,000 - RM 3,999",Malpemakanan,Daerah Barat Daya,...,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9

In [4]:
# Replace with the full path to your local CSV file
file_path = "D:/hp/Documents/Practicum/Code/Dataset/df_kids_PP.csv"

# Read the first line to count the number of columns
with open(file_path, 'r', encoding='utf-8') as x:
    ncols = len(x.readline().strip().split(','))

# Load CSV using the correct number of columns
df_kids_PP = pd.read_csv(file_path, usecols=range(0, ncols))

# Display the DataFrame
df_kids_PP.head()

,UMUR (BULAN),BANGSA,AGAMA,JANTINA,PENDAPATAN KELUARGA,GAJI BAPA,GAJI IBU,GAJI PENJAGA,STATUS PEMAKANAN,DAERAH,JENIS TASKA,TASKA_LOKASI,BMI
0,60,Melayu,Islam,LELAKI,M40,"RM 4,000 - RM 6,999","RM 4,000 - RM 6,999","RM 4,000 - RM 6,999",Malpemakanan,Seberang Perai Tengah,TASKA Institusi,BANDAR,Risiko berlebihan berat badan
1,54,Melayu,Islam,LELAKI,Tiada Maklumat,"RM 10,000 dan ke atas","RM 4,000 - RM 6,999","RM 4,000 - RM 6,999",Malpemakanan,Seberang Perai Tengah,TASKA Institusi,BANDAR,Berlebihan berat badan
2,53,Melayu,Islam,PEREMPUAN,B40,"RM 1,000 - RM 3,999","RM 1,000 - RM 3,999","RM 1,000 - RM 3,999",Malpemakanan,Seberang Perai Tengah,TASKA Di Rumah,BANDAR,Risiko berlebihan berat badan
3,52,Melayu,Islam,PEREMPUAN,B40,"RM 1,000 - RM 3,999","RM 1,000 - RM 3,999","RM 1,000 - RM 3,999",Malpemakanan,Seberang Perai Tengah,TASKA Institusi,BANDAR,Obes
4,58,Melayu,Islam,LELAKI,B40,"RM 1,000 - RM 3,999",TIADA MAKLUMAT GAJI,"RM 1,000 - RM 3,999",Malpemakanan,Daerah Barat Daya,"TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, Y...",LUAR BANDAR,Berlebihan berat badan

# Strategy: Drop Invalid Data

In [6]:
df_kids_DROP_INVALID = df_kids[df_kids['PENDAPATAN KELUARGA'] != 'Tiada Maklumat'].copy()
df_kids_DROP_INVALID.drop(columns=['GAJI BAPA', 'GAJI IBU', 'GAJI PENJAGA'], inplace=True)
df_kids_DROP_INVALID.head()

,UMUR (BULAN),BANGSA,AGAMA,JANTINA,PENDAPATAN KELUARGA,STATUS PEMAKANAN,DAERAH,JENIS TASKA,TASKA_LOKASI,BMI,banana_price,papaya_price,rice_price,bread_price,fish_price,chicken_price,carrot_price,tomato_price,cauliflower_price,milk_price
0,60,Melayu,Islam,LELAKI,M40,Malpemakanan,Seberang Perai Tengah,TASKA Institusi,BANDAR,Risiko berlebihan berat badan,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
2,53,Melayu,Islam,PEREMPUAN,B40,Malpemakanan,Seberang Perai Tengah,TASKA Di Rumah,BANDAR,Risiko berlebihan berat badan,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
3,52,Melayu,Islam,PEREMPUAN,B40,Malpemakanan,Seberang Perai Tengah,TASKA Institusi,BANDAR,Obes,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
4,58,Melayu,Islam,LELAKI,B40,Malpemakanan,Daerah Barat Daya,"TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, Y...",LUAR BANDAR,Berlebihan berat badan,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9
8,56,Melayu,Islam,PEREMPUAN,B40,Malpemakanan,Daerah Barat Daya,"TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, Y...",LUAR BANDAR,Berat badan normal,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9

In [7]:
df_kids_DROP_INVALID_FS = df_kids_PP[df_kids_PP['PENDAPATAN KELUARGA'] != 'Tiada Maklumat'].copy()
df_kids_DROP_INVALID_FS.drop(columns=['GAJI BAPA', 'GAJI IBU', 'GAJI PENJAGA'], inplace=True)
df_kids_DROP_INVALID_FS.head()

,UMUR (BULAN),BANGSA,AGAMA,JANTINA,PENDAPATAN KELUARGA,STATUS PEMAKANAN,DAERAH,JENIS TASKA,TASKA_LOKASI,BMI
0,60,Melayu,Islam,LELAKI,M40,Malpemakanan,Seberang Perai Tengah,TASKA Institusi,BANDAR,Risiko berlebihan berat badan
2,53,Melayu,Islam,PEREMPUAN,B40,Malpemakanan,Seberang Perai Tengah,TASKA Di Rumah,BANDAR,Risiko berlebihan berat badan
3,52,Melayu,Islam,PEREMPUAN,B40,Malpemakanan,Seberang Perai Tengah,TASKA Institusi,BANDAR,Obes
4,58,Melayu,Islam,LELAKI,B40,Malpemakanan,Daerah Barat Daya,"TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, Y...",LUAR BANDAR,Berlebihan berat badan
8,56,Melayu,Islam,PEREMPUAN,B40,Malpemakanan,Daerah Barat Daya,"TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, Y...",LUAR BANDAR,Berat badan normal

In [ ]:
export_path = "D:/hp/Documents/Practicum/Code/Dataset/df_kids_DROP_INVALID.csv"
df_kids_DROP_INVALID.to_csv(export_path, index=False)

export_path = "D:/hp/Documents/Practicum/Code/Dataset/df_kids_DROP_INVALID_FS.csv"
df_kids_DROP_INVALID_FS.to_csv(export_path, index=False)

# Strategy: Replace Invalid Data with Mode

In [9]:
df_kids_RP_MODE = df_kids.copy()
df_kids_RP_MODE['PENDAPATAN KELUARGA'].replace('Tiada Maklumat', df_kids_RP_MODE['PENDAPATAN KELUARGA'].mode()[0], inplace=True)
df_kids_RP_MODE.drop(columns=['GAJI BAPA', 'GAJI IBU', 'GAJI PENJAGA'], inplace=True)
df_kids_RP_MODE.head()

C:\Users\hp\AppData\Local\Temp\ipykernel_15312\1107637612.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_kids_RP_MODE['PENDAPATAN KELUARGA'].replace('Tiada Maklumat', df_kids_RP_MODE['PENDAPATAN KELUARGA'].mode()[0], inplace=True)

,UMUR (BULAN),BANGSA,AGAMA,JANTINA,PENDAPATAN KELUARGA,STATUS PEMAKANAN,DAERAH,JENIS TASKA,TASKA_LOKASI,BMI,banana_price,papaya_price,rice_price,bread_price,fish_price,chicken_price,carrot_price,tomato_price,cauliflower_price,milk_price
0,60,Melayu,Islam,LELAKI,M40,Malpemakanan,Seberang Perai Tengah,TASKA Institusi,BANDAR,Risiko berlebihan berat badan,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
1,54,Melayu,Islam,LELAKI,B40,Malpemakanan,Seberang Perai Tengah,TASKA Institusi,BANDAR,Berlebihan berat badan,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
2,53,Melayu,Islam,PEREMPUAN,B40,Malpemakanan,Seberang Perai Tengah,TASKA Di Rumah,BANDAR,Risiko berlebihan berat badan,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
3,52,Melayu,Islam,PEREMPUAN,B40,Malpemakanan,Seberang Perai Tengah,TASKA Institusi,BANDAR,Obes,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
4,58,Melayu,Islam,LELAKI,B40,Malpemakanan,Daerah Barat Daya,"TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, Y...",LUAR BANDAR,Berlebihan berat badan,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9

In [10]:
df_kids_RP_MODE_FS = df_kids_PP.copy()
df_kids_RP_MODE_FS['PENDAPATAN KELUARGA'].replace('Tiada Maklumat', df_kids_RP_MODE_FS['PENDAPATAN KELUARGA'].mode()[0], inplace=True)
df_kids_RP_MODE_FS.drop(columns=['GAJI BAPA', 'GAJI IBU', 'GAJI PENJAGA'], inplace=True)
df_kids_RP_MODE_FS.head()

C:\Users\hp\AppData\Local\Temp\ipykernel_15312\3000001126.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_kids_RP_MODE_FS['PENDAPATAN KELUARGA'].replace('Tiada Maklumat', df_kids_RP_MODE_FS['PENDAPATAN KELUARGA'].mode()[0], inplace=True)

,UMUR (BULAN),BANGSA,AGAMA,JANTINA,PENDAPATAN KELUARGA,STATUS PEMAKANAN,DAERAH,JENIS TASKA,TASKA_LOKASI,BMI
0,60,Melayu,Islam,LELAKI,M40,Malpemakanan,Seberang Perai Tengah,TASKA Institusi,BANDAR,Risiko berlebihan berat badan
1,54,Melayu,Islam,LELAKI,B40,Malpemakanan,Seberang Perai Tengah,TASKA Institusi,BANDAR,Berlebihan berat badan
2,53,Melayu,Islam,PEREMPUAN,B40,Malpemakanan,Seberang Perai Tengah,TASKA Di Rumah,BANDAR,Risiko berlebihan berat badan
3,52,Melayu,Islam,PEREMPUAN,B40,Malpemakanan,Seberang Perai Tengah,TASKA Institusi,BANDAR,Obes
4,58,Melayu,Islam,LELAKI,B40,Malpemakanan,Daerah Barat Daya,"TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, Y...",LUAR BANDAR,Berlebihan berat badan

In [ ]:
export_path = "D:/hp/Documents/Practicum/Code/Dataset/df_kids_RP_MODE.csv"
df_kids_RP_MODE.to_csv(export_path, index=False)

export_path = "D:/hp/Documents/Practicum/Code/Dataset/df_kids_RP_MODE_FS.csv"
df_kids_RP_MODE_FS.to_csv(export_path, index=False)