In [1]:
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# Before Feature Selection

In [2]:
file_path = "D:/hp/Documents/Practicum/Code/Dataset/kids_price.csv"

# Read the first line to count the number of columns
with open(file_path, 'r', encoding='utf-8') as x:
    ncols = len(x.readline().strip().split(','))

# Load CSV using the correct number of columns
df_kids = pd.read_csv(file_path, usecols=range(0, ncols))

# Display the DataFrame
df_kids.head()

,UMUR (BULAN),BANGSA,AGAMA,JANTINA,PENDAPATAN KELUARGA,GAJI BAPA,GAJI IBU,GAJI PENJAGA,STATUS PEMAKANAN,DAERAH,...,banana_price,papaya_price,rice_price,bread_price,fish_price,chicken_price,carrot_price,tomato_price,cauliflower_price,milk_price
0,60,Melayu,Islam,LELAKI,M40,"RM 4,000 - RM 6,999","RM 4,000 - RM 6,999","RM 4,000 - RM 6,999",Malpemakanan,Seberang Perai Tengah,...,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
1,54,Melayu,Islam,LELAKI,Tiada Maklumat,"RM 10,000 dan ke atas","RM 4,000 - RM 6,999","RM 4,000 - RM 6,999",Malpemakanan,Seberang Perai Tengah,...,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
2,53,Melayu,Islam,PEREMPUAN,B40,"RM 1,000 - RM 3,999","RM 1,000 - RM 3,999","RM 1,000 - RM 3,999",Malpemakanan,Seberang Perai Tengah,...,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
3,52,Melayu,Islam,PEREMPUAN,B40,"RM 1,000 - RM 3,999","RM 1,000 - RM 3,999","RM 1,000 - RM 3,999",Malpemakanan,Seberang Perai Tengah,...,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
4,58,Melayu,Islam,LELAKI,B40,"RM 1,000 - RM 3,999",TIADA MAKLUMAT GAJI,"RM 1,000 - RM 3,999",Malpemakanan,Daerah Barat Daya,...,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9

## Encoding Strategy

### Label Encoder

In [ ]:
# Create a LabelEncoder object
le = LabelEncoder()
df_kids_le = df_kids.copy()

# Iterate over the columns of the DataFrame
for col in df_kids_le.columns:
    # Check if the column is of object type (categorical)
    if df_kids_le[col].dtype == 'object':
        # Fit and transform the column using LabelEncoder
        df_kids_le[col] = le.fit_transform(df_kids_le[col])

df_kids_le.head()

,UMUR (BULAN),BANGSA,AGAMA,JANTINA,PENDAPATAN KELUARGA,GAJI BAPA,GAJI IBU,GAJI PENJAGA,STATUS PEMAKANAN,DAERAH,...,banana_price,papaya_price,rice_price,bread_price,fish_price,chicken_price,carrot_price,tomato_price,cauliflower_price,milk_price
0,60,5,2,0,1,4,4,4,1,3,...,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
1,54,5,2,0,4,3,4,4,1,3,...,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
2,53,5,2,1,0,2,2,2,1,3,...,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
3,52,5,2,1,0,2,2,2,1,3,...,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
4,58,5,2,0,0,2,6,2,1,0,...,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9

In [ ]:
x_le = df_kids_le.drop('BMI', axis=1)
y_le = df_kids_le['BMI']

x_train_le, x_test_le, y_train_le, y_test_le = train_test_split( x_le, y_le, test_size = 0.30, random_state=42, stratify=y_le)

In [ ]:
# Initialize and train the Logistic Regression model
model = LogisticRegression(max_iter=2000)
model.fit(x_train_le, y_train_le)
y_pred = model.predict(x_test_le)

In [ ]:
# Evaluate the model
print(confusion_matrix(y_test_le, y_pred))
print(classification_report(y_test_le, y_pred))

[[37  2  3 19  3  1]
 [ 0  6  5 18  1  1]
 [ 2  1  7 13  3  1]
 [10  5  3 27  2  0]
 [ 6  1  3  8  4  2]
 [ 1  2  3  2  4  0]]
              precision    recall  f1-score   support

           0       0.66      0.57      0.61        65
           1       0.35      0.19      0.25        31
           2       0.29      0.26      0.27        27
           3       0.31      0.57      0.40        47
           4       0.24      0.17      0.20        24
           5       0.00      0.00      0.00        12

    accuracy                           0.39       206
   macro avg       0.31      0.29      0.29       206
weighted avg       0.40      0.39      0.38       206

### One-Hot Encoder

In [ ]:
df_kids_ohe = df_kids.copy()
df_kids_ohe = df_kids_ohe.drop('BMI', axis=1)

In [ ]:
# Create a OneHotEncoder object
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

# Fit and transform the categorical columns
categorical_cols = df_kids_ohe.select_dtypes(include=['object']).columns
df_kids_encoded = pd.DataFrame(ohe.fit_transform(df_kids_ohe[categorical_cols]))

# Get feature names for the encoded columns
encoded_feature_names = list(ohe.get_feature_names_out(categorical_cols))
df_kids_encoded.columns = encoded_feature_names

# Drop original categorical columns from the dataframe
df_kids_ohe = df_kids_ohe.drop(categorical_cols, axis=1)

# Concatenate the encoded columns with the remaining numerical features
df_kids_ohe = pd.concat([df_kids_ohe, df_kids_encoded], axis=1)

df_kids_ohe.head()

,UMUR (BULAN),banana_price,papaya_price,rice_price,bread_price,fish_price,chicken_price,carrot_price,tomato_price,cauliflower_price,...,DAERAH_Seberang Perai Selatan,DAERAH_Seberang Perai Tengah,DAERAH_Seberang Perai Utara,"JENIS TASKA_TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, YPKT)",JENIS TASKA_TASKA Di Rumah,JENIS TASKA_TASKA Di Tempat Kerja (Sektor Awam),JENIS TASKA_TASKA Di Tempat Kerja (Sektor Swasta),JENIS TASKA_TASKA Institusi,TASKA_LOKASI_BANDAR,TASKA_LOKASI_LUAR BANDAR
0,60,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1,54,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
2,53,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,52,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
4,58,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
x_ohe = df_kids_ohe
y_ohe = df_kids['BMI']

x_train_ohe, x_test_ohe, y_train_ohe, y_test_ohe = train_test_split( x_ohe, y_ohe, test_size = 0.30, random_state=42, stratify=y_ohe)

In [ ]:
# Initialize and train the Logistic Regression model
model = LogisticRegression(max_iter=2000)
model.fit(x_train_ohe, y_train_ohe)
y_pred = model.predict(x_test_ohe)

In [ ]:
# Evaluate the model
print(confusion_matrix(y_test_ohe, y_pred))
print(classification_report(y_test_ohe, y_pred))

[[40  4  4 14  3  0]
 [ 7  3  7 12  1  1]
 [ 3  0  9 10  3  2]
 [15  6  5 17  3  1]
 [ 4  3  2  7  7  1]
 [ 3  1  0  5  3  0]]
                               precision    recall  f1-score   support

           Berat badan normal       0.56      0.62      0.58        65
       Berlebihan berat badan       0.18      0.10      0.12        31
                         Obes       0.33      0.33      0.33        27
Risiko berlebihan berat badan       0.26      0.36      0.30        47
                        Susut       0.35      0.29      0.32        24
                  Susut teruk       0.00      0.00      0.00        12

                     accuracy                           0.37       206
                    macro avg       0.28      0.28      0.28       206
                 weighted avg       0.35      0.37      0.35       206

## Use SMOTE(Synthetic Minority Over-sampling Technique) to solve class imbalance

### Label Encoder

In [ ]:
sm = SMOTE(random_state=42)
X_train_res, y_train_res = sm.fit_resample(x_train_le, y_train_le)

In [ ]:
# Initialize and train the Logistic Regression model
model = LogisticRegression(max_iter=2000) # Increased max_iter for convergence
model.fit(X_train_res, y_train_res)
y_pred = model.predict(x_test_le)

In [ ]:
# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test_le, y_pred))

print("\nClassification Report:")
print(classification_report(y_test_le, y_pred))

Confusion Matrix:
[[33  6  5 12  4  5]
 [ 0  8  7  8  3  5]
 [ 0  3 10  5  3  6]
 [ 6  9  5 21  3  3]
 [ 4  4  3  4  6  3]
 [ 1  2  5  1  3  0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.51      0.61        65
           1       0.25      0.26      0.25        31
           2       0.29      0.37      0.32        27
           3       0.41      0.45      0.43        47
           4       0.27      0.25      0.26        24
           5       0.00      0.00      0.00        12

    accuracy                           0.38       206
   macro avg       0.33      0.31      0.31       206
weighted avg       0.44      0.38      0.40       206

### One-Hot Encoder

In [ ]:
sm = SMOTE(random_state=42)
X_train_res, y_train_res = sm.fit_resample(x_train_ohe, y_train_ohe)

In [ ]:
# Initialize and train the Logistic Regression model
model = LogisticRegression(max_iter=2000) # Increased max_iter for convergence
model.fit(X_train_res, y_train_res)
y_pred = model.predict(x_test_ohe)

In [ ]:
# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test_ohe, y_pred))

print("\nClassification Report:")
print(classification_report(y_test_ohe, y_pred))

Confusion Matrix:
[[31  5  7 10  6  6]
 [ 0  6  9  9  3  4]
 [ 0  1 13  5  4  4]
 [ 5 13  7 12  5  5]
 [ 3  4  2  4  7  4]
 [ 0  0  3  3  5  1]]

Classification Report:
                               precision    recall  f1-score   support

           Berat badan normal       0.79      0.48      0.60        65
       Berlebihan berat badan       0.21      0.19      0.20        31
                         Obes       0.32      0.48      0.38        27
Risiko berlebihan berat badan       0.28      0.26      0.27        47
                        Susut       0.23      0.29      0.26        24
                  Susut teruk       0.04      0.08      0.06        12

                     accuracy                           0.34       206
                    macro avg       0.31      0.30      0.29       206
                 weighted avg       0.42      0.34      0.36       206

# After Feature Selection

## Strategy: Drop Invalid Data

In [3]:
file_path = "D:/hp/Documents/Practicum/Code/Dataset/DROP_INVALID_AfterFS.csv"

# Read the first line to count the number of columns
with open(file_path, 'r', encoding='utf-8') as x:
    ncols = len(x.readline().strip().split(','))

# Load CSV using the correct number of columns
df_DROP_INVALID_AfterFS = pd.read_csv(file_path, usecols=range(0, ncols))

# Display the DataFrame
df_DROP_INVALID_AfterFS.head()

,UMUR (BULAN),STATUS PEMAKANAN,JENIS TASKA,TASKA_LOKASI,BMI,banana_price,papaya_price,rice_price,bread_price,fish_price,chicken_price,carrot_price,tomato_price,cauliflower_price,milk_price
0,60,Malpemakanan,TASKA Institusi,BANDAR,Risiko berlebihan berat badan,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
1,53,Malpemakanan,TASKA Di Rumah,BANDAR,Risiko berlebihan berat badan,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
2,52,Malpemakanan,TASKA Institusi,BANDAR,Obes,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
3,58,Malpemakanan,"TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, Y...",LUAR BANDAR,Berlebihan berat badan,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9
4,56,Malpemakanan,"TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, Y...",LUAR BANDAR,Berat badan normal,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9

### Encoding Strategy

#### Label Encoder

In [ ]:
# Create a LabelEncoder object
le = LabelEncoder()
df_DROP_INVALID_AfterFS_le = df_DROP_INVALID_AfterFS.copy()

# Iterate over the columns of the DataFrame
for col in df_DROP_INVALID_AfterFS_le.columns:
    # Check if the column is of object type (categorical)
    if df_DROP_INVALID_AfterFS_le[col].dtype == 'object':
        # Fit and transform the column using LabelEncoder
        df_DROP_INVALID_AfterFS_le[col] = le.fit_transform(df_DROP_INVALID_AfterFS_le[col])

df_DROP_INVALID_AfterFS_le.head()

,UMUR (BULAN),STATUS PEMAKANAN,JENIS TASKA,TASKA_LOKASI,BMI,banana_price,papaya_price,rice_price,bread_price,fish_price,chicken_price,carrot_price,tomato_price,cauliflower_price,milk_price
0,60,0,4,0,3,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
1,53,0,1,0,3,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
2,52,0,4,0,2,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
3,58,0,0,1,1,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9
4,56,0,0,1,0,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9

In [ ]:
x_le = df_DROP_INVALID_AfterFS_le.drop('BMI', axis=1)
y_le = df_DROP_INVALID_AfterFS['BMI']

x_train_le, x_test_le, y_train_le, y_test_le = train_test_split( x_le, y_le, test_size = 0.30, random_state=42, stratify=y_le)

In [ ]:
# Initialize and train the Logistic Regression model
model = LogisticRegression(max_iter=2000)
model.fit(x_train_le, y_train_le)
y_pred = model.predict(x_test_le)

In [ ]:
# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test_le, y_pred))

print("\nClassification Report:")
print(classification_report(y_test_le, y_pred))

Confusion Matrix:
[[38  0  3 12  1  1]
 [ 2  2  2 16  2  0]
 [ 1  0  6 12  1  0]
 [ 7  5  3 24  1  0]
 [ 2  0  0 12  1  3]
 [ 1  0  1  5  2  1]]

Classification Report:
                               precision    recall  f1-score   support

           Berat badan normal       0.75      0.69      0.72        55
       Berlebihan berat badan       0.29      0.08      0.13        24
                         Obes       0.40      0.30      0.34        20
Risiko berlebihan berat badan       0.30      0.60      0.40        40
                        Susut       0.12      0.06      0.08        18
                  Susut teruk       0.20      0.10      0.13        10

                     accuracy                           0.43       167
                    macro avg       0.34      0.30      0.30       167
                 weighted avg       0.43      0.43      0.41       167

#### One-Hot Encoder

In [ ]:
df_DROP_INVALID_AfterFS_ohe = df_DROP_INVALID_AfterFS.copy()
df_DROP_INVALID_AfterFS_ohe = df_DROP_INVALID_AfterFS_ohe.drop('BMI', axis=1)

In [ ]:
# Create a OneHotEncoder object
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

# Fit and transform the categorical columns
categorical_cols = df_DROP_INVALID_AfterFS_ohe.select_dtypes(include=['object']).columns
df_DROP_INVALID_AfterFS_encoded = pd.DataFrame(ohe.fit_transform(df_DROP_INVALID_AfterFS_ohe[categorical_cols]))

# Get feature names for the encoded columns
encoded_feature_names = list(ohe.get_feature_names_out(categorical_cols))
df_DROP_INVALID_AfterFS_encoded.columns = encoded_feature_names

# Drop original categorical columns from the dataframe
df_DROP_INVALID_AfterFS_ohe = df_DROP_INVALID_AfterFS_ohe.drop(categorical_cols, axis=1)

# Concatenate the encoded columns with the remaining numerical features
df_DROP_INVALID_AfterFS_ohe = pd.concat([df_DROP_INVALID_AfterFS_ohe, df_DROP_INVALID_AfterFS_encoded], axis=1)

df_DROP_INVALID_AfterFS_ohe.head()

,UMUR (BULAN),banana_price,papaya_price,rice_price,bread_price,fish_price,chicken_price,carrot_price,tomato_price,cauliflower_price,milk_price,STATUS PEMAKANAN_Malpemakanan,STATUS PEMAKANAN_Normal,"JENIS TASKA_TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, YPKT)",JENIS TASKA_TASKA Di Rumah,JENIS TASKA_TASKA Di Tempat Kerja (Sektor Awam),JENIS TASKA_TASKA Di Tempat Kerja (Sektor Swasta),JENIS TASKA_TASKA Institusi,TASKA_LOKASI_BANDAR,TASKA_LOKASI_LUAR BANDAR
0,60,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1,53,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,52,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
3,58,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
4,56,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
x_ohe = df_DROP_INVALID_AfterFS_ohe
y_ohe = df_DROP_INVALID_AfterFS['BMI']

x_train_ohe, x_test_ohe, y_train_ohe, y_test_ohe = train_test_split( x_ohe, y_ohe, test_size = 0.30, random_state=42, stratify=y_ohe)

In [ ]:
# Initialize and train the Logistic Regression model
model = LogisticRegression(max_iter=2000)
model.fit(x_train_ohe, y_train_ohe)
y_pred = model.predict(x_test_ohe)

In [ ]:
# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test_ohe, y_pred))

print("\nClassification Report:")
print(classification_report(y_test_ohe, y_pred))

Confusion Matrix:
[[37  2  3 11  1  1]
 [ 2  2  5 15  0  0]
 [ 1  1  7 10  1  0]
 [ 7  3  5 25  0  0]
 [ 3  0  1 11  1  2]
 [ 1  1  1  3  3  1]]

Classification Report:
                               precision    recall  f1-score   support

           Berat badan normal       0.73      0.67      0.70        55
       Berlebihan berat badan       0.22      0.08      0.12        24
                         Obes       0.32      0.35      0.33        20
Risiko berlebihan berat badan       0.33      0.62      0.43        40
                        Susut       0.17      0.06      0.08        18
                  Susut teruk       0.25      0.10      0.14        10

                     accuracy                           0.44       167
                    macro avg       0.34      0.31      0.30       167
                 weighted avg       0.42      0.44      0.41       167

### Use SMOTE(Synthetic Minority Over-sampling Technique) to solve class imbalance

#### Label Encoder

In [ ]:
sm = SMOTE(random_state=42)
X_train_res, y_train_res = sm.fit_resample(x_train_le, y_train_le)

In [ ]:
# Initialize and train the Logistic Regression model
model = LogisticRegression(max_iter=2000) # Increased max_iter for convergence
model.fit(X_train_res, y_train_res)
y_pred = model.predict(x_test_le)

In [ ]:
# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test_le, y_pred))

print("\nClassification Report:")
print(classification_report(y_test_le, y_pred))

Confusion Matrix:
[[33  5  5  8  2  2]
 [ 2  2  9  6  3  2]
 [ 1  2 12  4  1  0]
 [ 7 10  7 10  3  3]
 [ 2  4  1  5  3  3]
 [ 1  0  4  0  4  1]]

Classification Report:
                               precision    recall  f1-score   support

           Berat badan normal       0.72      0.60      0.65        55
       Berlebihan berat badan       0.09      0.08      0.09        24
                         Obes       0.32      0.60      0.41        20
Risiko berlebihan berat badan       0.30      0.25      0.27        40
                        Susut       0.19      0.17      0.18        18
                  Susut teruk       0.09      0.10      0.10        10

                     accuracy                           0.37       167
                    macro avg       0.28      0.30      0.28       167
                 weighted avg       0.38      0.37      0.37       167

#### One-Hot Encoder

In [ ]:
sm = SMOTE(random_state=42)
X_train_res, y_train_res = sm.fit_resample(x_train_ohe, y_train_ohe)

In [ ]:
# Initialize and train the Logistic Regression model
model = LogisticRegression(max_iter=2000) # Increased max_iter for convergence
model.fit(X_train_res, y_train_res)
y_pred = model.predict(x_test_ohe)

In [ ]:
# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test_ohe, y_pred))

print("\nClassification Report:")
print(classification_report(y_test_ohe, y_pred))

Confusion Matrix:
[[31  6  7  6  3  2]
 [ 2  2 11  5  2  2]
 [ 1  1 13  5  0  0]
 [ 7  8 12  8  2  3]
 [ 2  1  2  4  6  3]
 [ 1  1  4  0  3  1]]

Classification Report:
                               precision    recall  f1-score   support

           Berat badan normal       0.70      0.56      0.63        55
       Berlebihan berat badan       0.11      0.08      0.09        24
                         Obes       0.27      0.65      0.38        20
Risiko berlebihan berat badan       0.29      0.20      0.24        40
                        Susut       0.38      0.33      0.35        18
                  Susut teruk       0.09      0.10      0.10        10

                     accuracy                           0.37       167
                    macro avg       0.30      0.32      0.30       167
                 weighted avg       0.39      0.37      0.36       167

## Strategy: Replace Invalid Data with Mode

In [4]:
file_path = "D:/hp/Documents/Practicum/Code/Dataset/RP_MODE_AfterFS.csv"

# Read the first line to count the number of columns
with open(file_path, 'r', encoding='utf-8') as x:
    ncols = len(x.readline().strip().split(','))

# Load CSV using the correct number of columns
df_RP_MODE_AfterFS = pd.read_csv(file_path, usecols=range(0, ncols))

# Display the DataFrame
df_RP_MODE_AfterFS.head()

,UMUR (BULAN),STATUS PEMAKANAN,JENIS TASKA,TASKA_LOKASI,BMI,banana_price,papaya_price,rice_price,bread_price,fish_price,chicken_price,carrot_price,tomato_price,cauliflower_price,milk_price
0,60,Malpemakanan,TASKA Institusi,BANDAR,Risiko berlebihan berat badan,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
1,54,Malpemakanan,TASKA Institusi,BANDAR,Berlebihan berat badan,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
2,53,Malpemakanan,TASKA Di Rumah,BANDAR,Risiko berlebihan berat badan,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
3,52,Malpemakanan,TASKA Institusi,BANDAR,Obes,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
4,58,Malpemakanan,"TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, Y...",LUAR BANDAR,Berlebihan berat badan,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9

### Encoding Strategy

#### Label Encoder

In [ ]:
# Create a LabelEncoder object
le = LabelEncoder()
df_RP_MODE_AfterFS_le = df_RP_MODE_AfterFS.copy()

# Iterate over the columns of the DataFrame
for col in df_RP_MODE_AfterFS_le.columns:
    # Check if the column is of object type (categorical)
    if df_RP_MODE_AfterFS_le[col].dtype == 'object':
        # Fit and transform the column using LabelEncoder
        df_RP_MODE_AfterFS_le[col] = le.fit_transform(df_RP_MODE_AfterFS_le[col])

df_RP_MODE_AfterFS_le.head()

,UMUR (BULAN),STATUS PEMAKANAN,JENIS TASKA,TASKA_LOKASI,BMI,banana_price,papaya_price,rice_price,bread_price,fish_price,chicken_price,carrot_price,tomato_price,cauliflower_price,milk_price
0,60,1,4,0,3,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
1,54,1,4,0,1,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
2,53,1,1,0,3,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
3,52,1,4,0,2,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
4,58,1,0,1,1,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9

In [ ]:
x_le = df_RP_MODE_AfterFS_le.drop('BMI', axis=1)
y_le = df_RP_MODE_AfterFS['BMI']

x_train_le, x_test_le, y_train_le, y_test_le = train_test_split( x_le, y_le, test_size = 0.30, random_state=42, stratify=y_le)

In [ ]:
# Initialize and train the Logistic Regression model
model = LogisticRegression(max_iter=2000)
model.fit(x_train_le, y_train_le)
y_pred = model.predict(x_test_le)

In [ ]:
# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test_le, y_pred))

print("\nClassification Report:")
print(classification_report(y_test_le, y_pred))

Confusion Matrix:
[[35  3  4 22  1  0]
 [ 1  1  6 22  1  0]
 [ 0  0  8 18  1  0]
 [ 5  1  3 36  2  0]
 [ 3  1  3 12  5  0]
 [ 1  1  2  5  3  0]]

Classification Report:
                               precision    recall  f1-score   support

           Berat badan normal       0.78      0.54      0.64        65
       Berlebihan berat badan       0.14      0.03      0.05        31
                         Obes       0.31      0.30      0.30        27
Risiko berlebihan berat badan       0.31      0.77      0.44        47
                        Susut       0.38      0.21      0.27        24
                  Susut teruk       0.00      0.00      0.00        12

                     accuracy                           0.41       206
                    macro avg       0.32      0.31      0.28       206
                 weighted avg       0.42      0.41      0.38       206

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

#### One-Hot Encoder

In [ ]:
df_RP_MODE_AfterFS_ohe = df_RP_MODE_AfterFS.copy()
df_RP_MODE_AfterFS_ohe = df_RP_MODE_AfterFS_ohe.drop('BMI', axis=1)

In [ ]:
# Create a OneHotEncoder object
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

# Fit and transform the categorical columns
categorical_cols = df_RP_MODE_AfterFS_ohe.select_dtypes(include=['object']).columns
df_RP_MODE_AfterFS_encoded = pd.DataFrame(ohe.fit_transform(df_RP_MODE_AfterFS_ohe[categorical_cols]))

# Get feature names for the encoded columns
encoded_feature_names = list(ohe.get_feature_names_out(categorical_cols))
df_RP_MODE_AfterFS_encoded.columns = encoded_feature_names

# Drop original categorical columns from the dataframe
df_RP_MODE_AfterFS_ohe = df_RP_MODE_AfterFS_ohe.drop(categorical_cols, axis=1)

# Concatenate the encoded columns with the remaining numerical features
df_RP_MODE_AfterFS_ohe = pd.concat([df_RP_MODE_AfterFS_ohe, df_RP_MODE_AfterFS_encoded], axis=1)

df_RP_MODE_AfterFS_ohe.head()

,UMUR (BULAN),banana_price,papaya_price,rice_price,bread_price,fish_price,chicken_price,carrot_price,tomato_price,cauliflower_price,...,STATUS PEMAKANAN_Error/Tiada Data,STATUS PEMAKANAN_Malpemakanan,STATUS PEMAKANAN_Normal,"JENIS TASKA_TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, YPKT)",JENIS TASKA_TASKA Di Rumah,JENIS TASKA_TASKA Di Tempat Kerja (Sektor Awam),JENIS TASKA_TASKA Di Tempat Kerja (Sektor Swasta),JENIS TASKA_TASKA Institusi,TASKA_LOKASI_BANDAR,TASKA_LOKASI_LUAR BANDAR
0,60,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1,54,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
2,53,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,52,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
4,58,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
x_ohe = df_RP_MODE_AfterFS_ohe
y_ohe = df_RP_MODE_AfterFS['BMI']

x_train_ohe, x_test_ohe, y_train_ohe, y_test_ohe = train_test_split( x_ohe, y_ohe, test_size = 0.30, random_state=42, stratify=y_ohe)

In [ ]:
# Initialize and train the Logistic Regression model
model = LogisticRegression(max_iter=2000)
model.fit(x_train_ohe, y_train_ohe)
y_pred = model.predict(x_test_ohe)

In [ ]:
# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test_ohe, y_pred))

print("\nClassification Report:")
print(classification_report(y_test_ohe, y_pred))

Confusion Matrix:
[[35  2  6 22  0  0]
 [ 2  1  8 20  0  0]
 [ 4  0 12 11  0  0]
 [ 7  2  3 32  3  0]
 [ 4  1  3  9  7  0]
 [ 2  1  2  5  2  0]]

Classification Report:
                               precision    recall  f1-score   support

           Berat badan normal       0.65      0.54      0.59        65
       Berlebihan berat badan       0.14      0.03      0.05        31
                         Obes       0.35      0.44      0.39        27
Risiko berlebihan berat badan       0.32      0.68      0.44        47
                        Susut       0.58      0.29      0.39        24
                  Susut teruk       0.00      0.00      0.00        12

                     accuracy                           0.42       206
                    macro avg       0.34      0.33      0.31       206
                 weighted avg       0.41      0.42      0.39       206

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

### Use SMOTE(Synthetic Minority Over-sampling Technique) to solve class imbalance

#### Label Encoder

In [ ]:
sm = SMOTE(random_state=42)
X_train_res, y_train_res = sm.fit_resample(x_train_le, y_train_le)

In [ ]:
# Initialize and train the Logistic Regression model
model = LogisticRegression(max_iter=2000) # Increased max_iter for convergence
model.fit(X_train_res, y_train_res)
y_pred = model.predict(x_test_le)

In [ ]:
# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test_le, y_pred))

print("\nClassification Report:")
print(classification_report(y_test_le, y_pred))

Confusion Matrix:
[[34  6  5 10  2  8]
 [ 0  5  8  9  4  5]
 [ 0  9 11  2  3  2]
 [ 4  9  6 15  5  8]
 [ 3  3  5  3  5  5]
 [ 1  1  5  0  3  2]]

Classification Report:
                               precision    recall  f1-score   support

           Berat badan normal       0.81      0.52      0.64        65
       Berlebihan berat badan       0.15      0.16      0.16        31
                         Obes       0.28      0.41      0.33        27
Risiko berlebihan berat badan       0.38      0.32      0.35        47
                        Susut       0.23      0.21      0.22        24
                  Susut teruk       0.07      0.17      0.10        12

                     accuracy                           0.35       206
                    macro avg       0.32      0.30      0.30       206
                 weighted avg       0.43      0.35      0.38       206

#### One-Hot Encoder

In [ ]:
sm = SMOTE(random_state=42)
X_train_res, y_train_res = sm.fit_resample(x_train_ohe, y_train_ohe)

In [ ]:
# Initialize and train the Logistic Regression model
model = LogisticRegression(max_iter=2000) # Increased max_iter for convergence
model.fit(X_train_res, y_train_res)
y_pred = model.predict(x_test_ohe)

In [ ]:
# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test_ohe, y_pred))

print("\nClassification Report:")
print(classification_report(y_test_ohe, y_pred))

Confusion Matrix:
[[31  8  8 10  3  5]
 [ 0  7  9  8  1  6]
 [ 0  7 15  2  1  2]
 [ 3 11  8 15  5  5]
 [ 3  5  4  3  5  4]
 [ 0  3  4  0  3  2]]

Classification Report:
                               precision    recall  f1-score   support

           Berat badan normal       0.84      0.48      0.61        65
       Berlebihan berat badan       0.17      0.23      0.19        31
                         Obes       0.31      0.56      0.40        27
Risiko berlebihan berat badan       0.39      0.32      0.35        47
                        Susut       0.28      0.21      0.24        24
                  Susut teruk       0.08      0.17      0.11        12

                     accuracy                           0.36       206
                    macro avg       0.35      0.33      0.32       206
                 weighted avg       0.46      0.36      0.39       206

# Model Tuning

In [5]:
file_path = "D:/hp/Documents/Practicum/Code/Dataset/DROP_INVALID_AfterFS.csv"

# Read the first line to count the number of columns
with open(file_path, 'r', encoding='utf-8') as x:
    ncols = len(x.readline().strip().split(','))

# Load CSV using the correct number of columns
df_DROP_INVALID_AfterFS = pd.read_csv(file_path, usecols=range(0, ncols))

# Display the DataFrame
df_DROP_INVALID_AfterFS.head()

,UMUR (BULAN),STATUS PEMAKANAN,JENIS TASKA,TASKA_LOKASI,BMI,banana_price,papaya_price,rice_price,bread_price,fish_price,chicken_price,carrot_price,tomato_price,cauliflower_price,milk_price
0,60,Malpemakanan,TASKA Institusi,BANDAR,Risiko berlebihan berat badan,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
1,53,Malpemakanan,TASKA Di Rumah,BANDAR,Risiko berlebihan berat badan,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
2,52,Malpemakanan,TASKA Institusi,BANDAR,Obes,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
3,58,Malpemakanan,"TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, Y...",LUAR BANDAR,Berlebihan berat badan,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9
4,56,Malpemakanan,"TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, Y...",LUAR BANDAR,Berat badan normal,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9

In [ ]:
df_DROP_INVALID_AfterFS_ohe = df_DROP_INVALID_AfterFS.copy()
df_DROP_INVALID_AfterFS_ohe = df_DROP_INVALID_AfterFS_ohe.drop('BMI', axis=1)

In [ ]:
# Create a OneHotEncoder object
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

# Fit and transform the categorical columns
categorical_cols = df_DROP_INVALID_AfterFS_ohe.select_dtypes(include=['object']).columns
df_DROP_INVALID_AfterFS_encoded = pd.DataFrame(ohe.fit_transform(df_DROP_INVALID_AfterFS_ohe[categorical_cols]))

# Get feature names for the encoded columns
encoded_feature_names = list(ohe.get_feature_names_out(categorical_cols))
df_DROP_INVALID_AfterFS_encoded.columns = encoded_feature_names

# Drop original categorical columns from the dataframe
df_DROP_INVALID_AfterFS_ohe = df_DROP_INVALID_AfterFS_ohe.drop(categorical_cols, axis=1)

# Concatenate the encoded columns with the remaining numerical features
df_DROP_INVALID_AfterFS_ohe = pd.concat([df_DROP_INVALID_AfterFS_ohe, df_DROP_INVALID_AfterFS_encoded], axis=1)

df_DROP_INVALID_AfterFS_ohe.head()

,UMUR (BULAN),banana_price,papaya_price,rice_price,bread_price,fish_price,chicken_price,carrot_price,tomato_price,cauliflower_price,milk_price,STATUS PEMAKANAN_Malpemakanan,STATUS PEMAKANAN_Normal,"JENIS TASKA_TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, YPKT)",JENIS TASKA_TASKA Di Rumah,JENIS TASKA_TASKA Di Tempat Kerja (Sektor Awam),JENIS TASKA_TASKA Di Tempat Kerja (Sektor Swasta),JENIS TASKA_TASKA Institusi,TASKA_LOKASI_BANDAR,TASKA_LOKASI_LUAR BANDAR
0,60,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1,53,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,52,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
3,58,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
4,56,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
x_ohe = df_DROP_INVALID_AfterFS_ohe
y_ohe = df_DROP_INVALID_AfterFS['BMI']

x_train, x_test, y_train, y_test = train_test_split( x_ohe, y_ohe, test_size = 0.30, random_state=42, stratify=y_ohe)

## L2 Regularization

In [ ]:
param_grid = {
        'penalty': ['l2'],
        'C': [0.01, 0.1, 1, 10, 100],
        'solver': ['lbfgs', 'saga'],
        'class_weight': [None, 'balanced'],
        'max_iter': [100, 500, 1000, 2000, 5000],
        'fit_intercept': [True, False]}

In [ ]:
grid_search = GridSearchCV(estimator=LogisticRegression(),
                           param_grid=param_grid,
                           cv=5,
                           scoring='accuracy',
                           n_jobs=-1,
                           verbose=2)

grid_search.fit(x_train, y_train)

Fitting 5 folds for each of 200 candidates, totalling 1000 fits

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

GridSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [0.01, 0.1, 1, 10, 100],
                         'class_weight': [None, 'balanced'],
                         'fit_intercept': [True, False],
                         'max_iter': [100, 500, 1000, 2000, 5000],
                         'penalty': ['l2'], 'solver': ['lbfgs', 'saga']},
             scoring='accuracy', verbose=2)

In [ ]:
# Print the best parameters and best score
print("Best parameters found: ", grid_search.best_params_)
print("Best accuracy found: ", grid_search.best_score_)

Best parameters found:  {'C': 1, 'class_weight': None, 'fit_intercept': True, 'max_iter': 1000, 'penalty': 'l2', 'solver': 'saga'}
Best accuracy found:  0.42350982350982347

In [ ]:
# Get the best model from the grid search
best_rf_model = grid_search.best_estimator_

# Make predictions on the test set using the best model
tuned_predictions = best_rf_model.predict(x_test)

# Evaluate the tuned model
print("\nTuned Model Confusion Matrix:")
print(confusion_matrix(y_test, tuned_predictions))

print("\nTuned Model Classification Report:")
print(classification_report(y_test, tuned_predictions))

Tuned Model Confusion Matrix:
[[38  1  3 11  1  1]
 [ 2  2  5 15  0  0]
 [ 1  0  8 10  1  0]
 [ 7  3  4 26  0  0]
 [ 3  0  1 11  1  2]
 [ 1  0  3  3  2  1]]

Tuned Model Classification Report:
                               precision    recall  f1-score   support

           Berat badan normal       0.73      0.69      0.71        55
       Berlebihan berat badan       0.33      0.08      0.13        24
                         Obes       0.33      0.40      0.36        20
Risiko berlebihan berat badan       0.34      0.65      0.45        40
                        Susut       0.20      0.06      0.09        18
                  Susut teruk       0.25      0.10      0.14        10

                     accuracy                           0.46       167
                    macro avg       0.36      0.33      0.31       167
                 weighted avg       0.45      0.46      0.42       167

## No Regularization

In [ ]:
param_grid = {
        'penalty': [None],
        'solver': ['lbfgs', 'saga'],
        'class_weight': [None, 'balanced'],
        'max_iter': [100, 500, 1000, 2000, 5000],
        'fit_intercept': [True, False]}

In [ ]:
grid_search = GridSearchCV(estimator=LogisticRegression(),
                           param_grid=param_grid,
                           cv=5,
                           scoring='accuracy',
                           n_jobs=-1,
                           verbose=2)

grid_search.fit(x_train, y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

GridSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'class_weight': [None, 'balanced'],
                         'fit_intercept': [True, False],
                         'max_iter': [100, 500, 1000, 2000, 5000],
                         'penalty': [None], 'solver': ['lbfgs', 'saga']},
             scoring='accuracy', verbose=2)

In [ ]:
# Print the best parameters and best score
print("Best parameters found: ", grid_search.best_params_)
print("Best accuracy found: ", grid_search.best_score_)

Best parameters found:  {'class_weight': None, 'fit_intercept': True, 'max_iter': 2000, 'penalty': None, 'solver': 'saga'}
Best accuracy found:  0.41841491841491846

In [ ]:
# Get the best model from the grid search
best_rf_model = grid_search.best_estimator_

# Make predictions on the test set using the best model
tuned_predictions = best_rf_model.predict(x_test)

# Evaluate the tuned model
print("\nTuned Model Confusion Matrix:")
print(confusion_matrix(y_test, tuned_predictions))

print("\nTuned Model Classification Report:")
print(classification_report(y_test, tuned_predictions))

Tuned Model Confusion Matrix:
[[36  3  3 10  2  1]
 [ 2  2  5 15  0  0]
 [ 2  1  7  9  1  0]
 [ 7  6  5 22  0  0]
 [ 2  0  1 11  1  3]
 [ 1  0  2  3  3  1]]

Tuned Model Classification Report:
                               precision    recall  f1-score   support

           Berat badan normal       0.72      0.65      0.69        55
       Berlebihan berat badan       0.17      0.08      0.11        24
                         Obes       0.30      0.35      0.33        20
Risiko berlebihan berat badan       0.31      0.55      0.40        40
                        Susut       0.14      0.06      0.08        18
                  Susut teruk       0.20      0.10      0.13        10

                     accuracy                           0.41       167
                    macro avg       0.31      0.30      0.29       167
                 weighted avg       0.40      0.41      0.39       167

## L1 Regularization

In [ ]:
param_grid = {
        'penalty': ['l1'],
        'C': [0.01, 0.1, 1, 10, 100],
        'solver': ['liblinear', 'saga'],
        'class_weight': [None, 'balanced'],
        'max_iter': [100, 500, 1000],
        'fit_intercept': [True, False]}

In [ ]:
grid_search = GridSearchCV(estimator=LogisticRegression(),
                           param_grid=param_grid,
                           cv=5,
                           scoring='accuracy',
                           n_jobs=-1,
                           verbose=2)

grid_search.fit(x_train, y_train)

Fitting 5 folds for each of 120 candidates, totalling 600 fits

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

GridSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [0.01, 0.1, 1, 10, 100],
                         'class_weight': [None, 'balanced'],
                         'fit_intercept': [True, False],
                         'max_iter': [100, 500, 1000], 'penalty': ['l1'],
                         'solver': ['liblinear', 'saga']},
             scoring='accuracy', verbose=2)

In [ ]:
# Print the best parameters and best score
print("Best parameters found: ", grid_search.best_params_)
print("Best accuracy found: ", grid_search.best_score_)

Best parameters found:  {'C': 10, 'class_weight': None, 'fit_intercept': True, 'max_iter': 1000, 'penalty': 'l1', 'solver': 'saga'}
Best accuracy found:  0.42350982350982347

In [ ]:
# Get the best model from the grid search
best_rf_model = grid_search.best_estimator_

# Make predictions on the test set using the best model
tuned_predictions = best_rf_model.predict(x_test)

# Evaluate the tuned model
print("\nTuned Model Confusion Matrix:")
print(confusion_matrix(y_test, tuned_predictions))

print("\nTuned Model Classification Report:")
print(classification_report(y_test, tuned_predictions))

Tuned Model Confusion Matrix:
[[38  1  3 11  1  1]
 [ 2  2  5 15  0  0]
 [ 1  0  8 10  1  0]
 [ 7  3  5 25  0  0]
 [ 3  0  1 11  1  2]
 [ 1  0  3  2  3  1]]

Tuned Model Classification Report:
                               precision    recall  f1-score   support

           Berat badan normal       0.73      0.69      0.71        55
       Berlebihan berat badan       0.33      0.08      0.13        24
                         Obes       0.32      0.40      0.36        20
Risiko berlebihan berat badan       0.34      0.62      0.44        40
                        Susut       0.17      0.06      0.08        18
                  Susut teruk       0.25      0.10      0.14        10

                     accuracy                           0.45       167
                    macro avg       0.36      0.33      0.31       167
                 weighted avg       0.44      0.45      0.42       167

## Elastic Net Regularization

In [ ]:
param_grid = {
        'penalty': ['elasticnet'],
        'C': [0.01, 0.1, 1, 10],
        'solver': ['saga'],
        'l1_ratio': [0.2, 0.5, 0.8],  # ElasticNet mixing
        'class_weight': [None, 'balanced'],
        'max_iter': [500, 1000],
        'fit_intercept': [True, False]}

In [ ]:
grid_search = GridSearchCV(estimator=LogisticRegression(),
                           param_grid=param_grid,
                           cv=5,
                           scoring='accuracy',
                           n_jobs=-1,
                           verbose=2)

grid_search.fit(x_train, y_train)

Fitting 5 folds for each of 96 candidates, totalling 480 fits

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

GridSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [0.01, 0.1, 1, 10],
                         'class_weight': [None, 'balanced'],
                         'fit_intercept': [True, False],
                         'l1_ratio': [0.2, 0.5, 0.8], 'max_iter': [500, 1000],
                         'penalty': ['elasticnet'], 'solver': ['saga']},
             scoring='accuracy', verbose=2)

In [ ]:
# Print the best parameters and best score
print("Best parameters found: ", grid_search.best_params_)
print("Best accuracy found: ", grid_search.best_score_)

Best parameters found:  {'C': 10, 'class_weight': None, 'fit_intercept': True, 'l1_ratio': 0.8, 'max_iter': 1000, 'penalty': 'elasticnet', 'solver': 'saga'}
Best accuracy found:  0.42350982350982347

In [ ]:
# Get the best model from the grid search
best_rf_model = grid_search.best_estimator_

# Make predictions on the test set using the best model
tuned_predictions = best_rf_model.predict(x_test)

# Evaluate the tuned model
print("\nTuned Model Confusion Matrix:")
print(confusion_matrix(y_test, tuned_predictions))

print("\nTuned Model Classification Report:")
print(classification_report(y_test, tuned_predictions))

Tuned Model Confusion Matrix:
[[38  1  3 11  1  1]
 [ 2  2  5 15  0  0]
 [ 1  0  8 10  1  0]
 [ 7  3  5 25  0  0]
 [ 3  0  1 11  1  2]
 [ 1  0  3  2  3  1]]

Tuned Model Classification Report:
                               precision    recall  f1-score   support

           Berat badan normal       0.73      0.69      0.71        55
       Berlebihan berat badan       0.33      0.08      0.13        24
                         Obes       0.32      0.40      0.36        20
Risiko berlebihan berat badan       0.34      0.62      0.44        40
                        Susut       0.17      0.06      0.08        18
                  Susut teruk       0.25      0.10      0.14        10

                     accuracy                           0.45       167
                    macro avg       0.36      0.33      0.31       167
                 weighted avg       0.44      0.45      0.42       167

# Number of Target Labels

In [3]:
file_path = "D:/hp/Documents/Practicum/Code/Dataset/DROP_INVALID_AfterFS.csv"

# Read the first line to count the number of columns
with open(file_path, 'r', encoding='utf-8') as x:
    ncols = len(x.readline().strip().split(','))

# Load CSV using the correct number of columns
df_DROP_INVALID_AfterFS = pd.read_csv(file_path, usecols=range(0, ncols))

# Display the DataFrame
df_DROP_INVALID_AfterFS.head()

,UMUR (BULAN),STATUS PEMAKANAN,JENIS TASKA,TASKA_LOKASI,BMI,banana_price,papaya_price,rice_price,bread_price,fish_price,chicken_price,carrot_price,tomato_price,cauliflower_price,milk_price
0,60,Malpemakanan,TASKA Institusi,BANDAR,Risiko berlebihan berat badan,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
1,53,Malpemakanan,TASKA Di Rumah,BANDAR,Risiko berlebihan berat badan,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
2,52,Malpemakanan,TASKA Institusi,BANDAR,Obes,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9
3,58,Malpemakanan,"TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, Y...",LUAR BANDAR,Berlebihan berat badan,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9
4,56,Malpemakanan,"TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, Y...",LUAR BANDAR,Berat badan normal,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9

## 4 Labels

In [ ]:
df = df_DROP_INVALID_AfterFS.replace({'BMI': {"Berat badan normal": "Normal",
                                                 "Berlebihan berat badan": "Berat berlebihan",
                                                 "Obes": "Berat berlebihan",
                                                 "Risiko berlebihan berat badan": "Berisiko",
                                                 "Susut": "Kurang berat badan",
                                                 "Susut teruk": "Kurang berat badan"}})

In [ ]:
df_DROP_INVALID_AfterFS_ohe = df.copy()
df_DROP_INVALID_AfterFS_ohe = df_DROP_INVALID_AfterFS_ohe.drop('BMI', axis=1)

In [ ]:
# Create a OneHotEncoder object
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

# Fit and transform the categorical columns
categorical_cols = df_DROP_INVALID_AfterFS_ohe.select_dtypes(include=['object']).columns
df_DROP_INVALID_AfterFS_encoded = pd.DataFrame(ohe.fit_transform(df_DROP_INVALID_AfterFS_ohe[categorical_cols]))

# Get feature names for the encoded columns
encoded_feature_names = list(ohe.get_feature_names_out(categorical_cols))
df_DROP_INVALID_AfterFS_encoded.columns = encoded_feature_names

# Drop original categorical columns from the dataframe
df_DROP_INVALID_AfterFS_ohe = df_DROP_INVALID_AfterFS_ohe.drop(categorical_cols, axis=1)

# Concatenate the encoded columns with the remaining numerical features
df_DROP_INVALID_AfterFS_ohe = pd.concat([df_DROP_INVALID_AfterFS_ohe, df_DROP_INVALID_AfterFS_encoded], axis=1)

df_DROP_INVALID_AfterFS_ohe.head()

,UMUR (BULAN),banana_price,papaya_price,rice_price,bread_price,fish_price,chicken_price,carrot_price,tomato_price,cauliflower_price,milk_price,STATUS PEMAKANAN_Malpemakanan,STATUS PEMAKANAN_Normal,"JENIS TASKA_TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, YPKT)",JENIS TASKA_TASKA Di Rumah,JENIS TASKA_TASKA Di Tempat Kerja (Sektor Awam),JENIS TASKA_TASKA Di Tempat Kerja (Sektor Swasta),JENIS TASKA_TASKA Institusi,TASKA_LOKASI_BANDAR,TASKA_LOKASI_LUAR BANDAR
0,60,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1,53,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,52,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
3,58,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
4,56,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
x_ohe = df_DROP_INVALID_AfterFS_ohe
y_ohe = df['BMI']

x_train_ohe, x_test_ohe, y_train_ohe, y_test_ohe = train_test_split(x_ohe, y_ohe, test_size = 0.30, random_state=42, stratify=y_ohe)

In [ ]:
# Initialize and train the Logistic Regression model
model = LogisticRegression(C=1, class_weight=None, fit_intercept=True, max_iter=1000, penalty='l2', solver='saga')
model.fit(x_train_ohe, y_train_ohe)
y_pred = model.predict(x_test_ohe)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

In [ ]:
# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test_ohe, y_pred))

print("\nClassification Report:")
print(classification_report(y_test_ohe, y_pred))

Confusion Matrix:
[[23 15  5  1]
 [13 16  4  7]
 [ 7  6 14  1]
 [ 9 11  2 33]]

Classification Report:
                    precision    recall  f1-score   support

  Berat berlebihan       0.44      0.52      0.48        44
          Berisiko       0.33      0.40      0.36        40
Kurang berat badan       0.56      0.50      0.53        28
            Normal       0.79      0.60      0.68        55

          accuracy                           0.51       167
         macro avg       0.53      0.51      0.51       167
      weighted avg       0.55      0.51      0.53       167

## 3 Labels

In [4]:
df = df_DROP_INVALID_AfterFS.replace({'BMI': {"Berat badan normal": "Normal",
                                                 "Berlebihan berat badan": "Berat berlebihan",
                                                 "Obes": "Berat berlebihan",
                                                 "Risiko berlebihan berat badan": "Berat berlebihan",
                                                 "Susut": "Kurang berat badan",
                                                 "Susut teruk": "Kurang berat badan"}})

In [5]:
df_DROP_INVALID_AfterFS_ohe = df.copy()
df_DROP_INVALID_AfterFS_ohe = df_DROP_INVALID_AfterFS_ohe.drop('BMI', axis=1)

In [6]:
# Create a OneHotEncoder object
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

# Fit and transform the categorical columns
categorical_cols = df_DROP_INVALID_AfterFS_ohe.select_dtypes(include=['object']).columns
df_DROP_INVALID_AfterFS_encoded = pd.DataFrame(ohe.fit_transform(df_DROP_INVALID_AfterFS_ohe[categorical_cols]))

# Get feature names for the encoded columns
encoded_feature_names = list(ohe.get_feature_names_out(categorical_cols))
df_DROP_INVALID_AfterFS_encoded.columns = encoded_feature_names

# Drop original categorical columns from the dataframe
df_DROP_INVALID_AfterFS_ohe = df_DROP_INVALID_AfterFS_ohe.drop(categorical_cols, axis=1)

# Concatenate the encoded columns with the remaining numerical features
df_DROP_INVALID_AfterFS_ohe = pd.concat([df_DROP_INVALID_AfterFS_ohe, df_DROP_INVALID_AfterFS_encoded], axis=1)

df_DROP_INVALID_AfterFS_ohe.head()

,UMUR (BULAN),banana_price,papaya_price,rice_price,bread_price,fish_price,chicken_price,carrot_price,tomato_price,cauliflower_price,milk_price,STATUS PEMAKANAN_Malpemakanan,STATUS PEMAKANAN_Normal,"JENIS TASKA_TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, YPKT)",JENIS TASKA_TASKA Di Rumah,JENIS TASKA_TASKA Di Tempat Kerja (Sektor Awam),JENIS TASKA_TASKA Di Tempat Kerja (Sektor Swasta),JENIS TASKA_TASKA Institusi,TASKA_LOKASI_BANDAR,TASKA_LOKASI_LUAR BANDAR
0,60,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1,53,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,52,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
3,58,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
4,56,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [7]:
x_ohe = df_DROP_INVALID_AfterFS_ohe
y_ohe = df['BMI']

x_train_ohe, x_test_ohe, y_train_ohe, y_test_ohe = train_test_split(x_ohe, y_ohe, test_size = 0.30, random_state=42, stratify=y_ohe)

In [13]:
# Initialize and train the Logistic Regression model
model = LogisticRegression(C=1, class_weight=None, fit_intercept=True, max_iter=1000, penalty='l2', solver='saga')
model.fit(x_train_ohe, y_train_ohe)
y_pred = model.predict(x_test_ohe)

c:\Users\hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

In [14]:
# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test_ohe, y_pred))

print("\nClassification Report:")
print(classification_report(y_test_ohe, y_pred))

Confusion Matrix:
[[71  3 10]
 [20  4  4]
 [18  1 36]]

Classification Report:
                    precision    recall  f1-score   support

  Berat berlebihan       0.65      0.85      0.74        84
Kurang berat badan       0.50      0.14      0.22        28
            Normal       0.72      0.65      0.69        55

          accuracy                           0.66       167
         macro avg       0.62      0.55      0.55       167
      weighted avg       0.65      0.66      0.63       167

## 2 Labels (Binary)

In [ ]:
df = df_DROP_INVALID_AfterFS.replace({'BMI': {"Berat badan normal": "Normal",
                                                 "Berlebihan berat badan": "Abnormal",
                                                 "Obes": "Abnormal",
                                                 "Risiko berlebihan berat badan": "Abnormal",
                                                 "Susut": "Abnormal",
                                                 "Susut teruk": "Abnormal"}})

In [ ]:
df_DROP_INVALID_AfterFS_ohe = df.copy()
df_DROP_INVALID_AfterFS_ohe = df_DROP_INVALID_AfterFS_ohe.drop('BMI', axis=1)

In [ ]:
# Create a OneHotEncoder object
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

# Fit and transform the categorical columns
categorical_cols = df_DROP_INVALID_AfterFS_ohe.select_dtypes(include=['object']).columns
df_DROP_INVALID_AfterFS_encoded = pd.DataFrame(ohe.fit_transform(df_DROP_INVALID_AfterFS_ohe[categorical_cols]))

# Get feature names for the encoded columns
encoded_feature_names = list(ohe.get_feature_names_out(categorical_cols))
df_DROP_INVALID_AfterFS_encoded.columns = encoded_feature_names

# Drop original categorical columns from the dataframe
df_DROP_INVALID_AfterFS_ohe = df_DROP_INVALID_AfterFS_ohe.drop(categorical_cols, axis=1)

# Concatenate the encoded columns with the remaining numerical features
df_DROP_INVALID_AfterFS_ohe = pd.concat([df_DROP_INVALID_AfterFS_ohe, df_DROP_INVALID_AfterFS_encoded], axis=1)

df_DROP_INVALID_AfterFS_ohe.head()

,UMUR (BULAN),banana_price,papaya_price,rice_price,bread_price,fish_price,chicken_price,carrot_price,tomato_price,cauliflower_price,milk_price,STATUS PEMAKANAN_Malpemakanan,STATUS PEMAKANAN_Normal,"JENIS TASKA_TASKA Agensi Kerajaan (GENIUS, KEMAS, JPNIN, YPKT)",JENIS TASKA_TASKA Di Rumah,JENIS TASKA_TASKA Di Tempat Kerja (Sektor Awam),JENIS TASKA_TASKA Di Tempat Kerja (Sektor Swasta),JENIS TASKA_TASKA Institusi,TASKA_LOKASI_BANDAR,TASKA_LOKASI_LUAR BANDAR
0,60,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1,53,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,52,6.0,4.29,25.99,2.8,9.99,8.9,4.49,5.00,7.9,20.9,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
3,58,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
4,56,6.0,4.50,25.90,2.8,10.00,8.9,5.00,5.49,8.0,20.9,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
x_ohe = df_DROP_INVALID_AfterFS_ohe
y_ohe = df['BMI']

x_train_ohe, x_test_ohe, y_train_ohe, y_test_ohe = train_test_split(x_ohe, y_ohe, test_size = 0.30, random_state=42, stratify=y_ohe)

In [ ]:
# Initialize and train the Logistic Regression model
model = LogisticRegression(C=1, class_weight=None, fit_intercept=True, max_iter=1000, penalty='l2', solver='saga')
model.fit(x_train_ohe, y_train_ohe)
y_pred = model.predict(x_test_ohe)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

In [ ]:
# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test_ohe, y_pred))

print("\nClassification Report:")
print(classification_report(y_test_ohe, y_pred))

Confusion Matrix:
[[102  10]
 [ 19  36]]

Classification Report:
              precision    recall  f1-score   support

    Abnormal       0.84      0.91      0.88       112
      Normal       0.78      0.65      0.71        55

    accuracy                           0.83       167
   macro avg       0.81      0.78      0.79       167
weighted avg       0.82      0.83      0.82       167